//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub mod prelude;

pub mod category_fishes;
pub mod example_table;
pub mod limitations;
pub mod monitoring_data;
pub mod monitorings;
pub mod users;
