//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::category_fishes::Entity as CategoryFishes;
pub use super::example_table::Entity as ExampleTable;
pub use super::limitations::Entity as Limitations;
pub use super::monitoring_data::Entity as MonitoringData;
pub use super::monitorings::Entity as Monitorings;
pub use super::users::Entity as Users;
